pipeline {
    agent any
         environment {
            imagename = "d107final/docker-be"
            registryCredential = 'jumzip@d107'
            dockerImage = ''
        }

    //tools {}
    stages {
        stage('start') {
            steps { echo '[process START] (o゜▽゜)o---☆ *:･.:･ﾟ*' }
        }

        stage('git clone') {
            steps {
                checkout scmGit(
                    branches: [[name: 'dev-be']],
                    extensions: [],
                    userRemoteConfigs: [[
                        credentialsId: 'BEmanager',
                        url: 'https://lab.ssafy.com/s08-final/S08P31D107.git'
                    ]]
                )
            }
            post {
                success { echo 'clone Git complete!!!' }
                failure { echo '[error] git clone FAIL (╯°□°）╯︵ ┻━┻ ' }
            }
        }

        stage('build Gradle') {

            steps {
                dir('backend/Arcana') {

                    //현재 dir 체크
                    script {
                        def pwd = sh(script: 'pwd', returnStdout: true).trim()
                        echo "Current directory : ${pwd}"
                    }

                    echo "build Gradle..."

                    sh "chmod +x gradlew"
                    sh "./gradlew clean build"
                }
            }

            post {
                success { echo 'build Gradle complete!!!' }
                failure { echo '[error] build Gradle FAIL (╯°□°）╯︵ ┻━┻ ' }
            }
        }

        stage('build Docker') {

            steps {
                dir('backend/Arcana') {

                    echo 'build Docker...'

                    //현재 dir 체크
                    script {
                        def pwd = sh(script: 'pwd', returnStdout: true).trim()
                        echo "Current directory : ${pwd}"

                        dockerImage = docker.build imagename
                    }
                }
            }

            post {
                success { echo 'build Docker complete!!!' }
                failure { echo '[error] build Docker FAIL (╯°□°）╯︵ ┻━┻ ' }
            }
        }

        stage('push Docker') {
            steps {
                echo 'push Docker...'
                    script {
                        sh 'docker push d107final/docker-be'
                    }
            }

            post {
                success { echo 'build Docker complete!!!' }
                failure { echo '[error] push Docker FAIL (╯°□°）╯︵ ┻━┻ ' }
            }
        }

        stage('run Docker') {
            steps {
                echo 'pull Docker...'

                sh 'docker pull d107final/docker-be'

                echo 'Clean image...'
                sh '''
                    if test "`docker ps -aq --filter name=docker-be`"; then
                    docker stop docker-be
                    docker rm docker-be
                    fi
                '''

                echo 'run Docker...'
                // 도커 중복시 삭제하고 덮어씌우기 처리 안했으니까 해야함
                sh 'docker run -d --name docker-be -p 18081:18081 d107final/docker-be'

            }
        }
    }
}
