pipeline {
    agent any
    /*     environment {
            // docker 설치 후 작성(도커 레포,id)

        }

    tools {} */
    stages {
        stage('start') {
            steps { echo '[process START] (o゜▽゜)o---☆ *:･.:･ﾟ*' }
        }

        stage('git clone') {
            steps {
                checkout scmGit(
                    branches: [[name: 'buildtest']],
                    extensions: [],
                    userRemoteConfigs: [[
                        credentialsId: 'testcred',
                        url: 'https://lab.ssafy.com/s08-final/S08P31D107.git'
                    ]]
                )
                echo 'clone Git complete!!!'
            }

            post { failure { echo '[error] git clone FAIL (╯°□°）╯︵ ┻━┻ ' } }
        }

        stage('build Gradle') {

            steps {
                dir('backend/Arcana') {
                    script {
                        def pwd = sh(script: 'pwd', returnStdout: true).trim()
                        echo "Current directory : ${pwd}"
                    }

                    echo "build Gradle..."

                    sh "chmod +x gradlew"
                    sh "./gradlew clean build"
                }

                echo "build Gradle complete!!!"
            }

            post { failure { echo '[error] build Gradle FAIL (╯°□°）╯︵ ┻━┻ ' } }
        }
        /* stage('build Docker') {}
        stage('') */
    }
}