export interface TarotType {
  id: number;
  name: string;
  class: string;
  number: number;
  reverse: boolean;
}

export const tarot: Array<TarotType> = [
  {
    id: 0,
    name: 'The Fool',
    class: 'major',
    number: 0,
    reverse: false,
  },
  {
    id: 1,
    name: 'The Magician',
    class: 'major',
    number: 1,
    reverse: false,
  },
  {
    id: 2,
    name: 'The High Priestess',
    class: 'major',
    number: 2,
    reverse: false,
  },
  {
    id: 3,
    name: 'The Empress',
    class: 'major',
    number: 3,
    reverse: false,
  },
  {
    id: 4,
    name: 'The Emperor',
    class: 'major',
    number: 4,
    reverse: false,
  },
  {
    id: 5,
    name: 'The Hierophant',
    class: 'major',
    number: 5,
    reverse: false,
  },
  {
    id: 6,
    name: 'The Lovers',
    class: 'major',
    number: 6,
    reverse: false,
  },
  {
    id: 7,
    name: 'The Chariot',
    class: 'major',
    number: 7,
    reverse: false,
  },
  {
    id: 8,
    name: 'Strength',
    class: 'major',
    number: 8,
    reverse: false,
  },
  {
    id: 9,
    name: 'The Hermit',
    class: 'major',
    number: 9,
    reverse: false,
  },
  {
    id: 10,
    name: 'Wheel of Fortune',
    class: 'major',
    number: 10,
    reverse: false,
  },
  {
    id: 11,
    name: 'Justice',
    class: 'major',
    number: 11,
    reverse: false,
  },
  {
    id: 12,
    name: 'The Hanged Man',
    class: 'major',
    number: 12,
    reverse: false,
  },
  {
    id: 13,
    name: 'Death',
    class: 'major',
    number: 13,
    reverse: false,
  },
  {
    id: 14,
    name: 'Temperance',
    class: 'major',
    number: 14,
    reverse: false,
  },
  {
    id: 15,
    name: 'The Devil',
    class: 'major',
    number: 15,
    reverse: false,
  },
  {
    id: 16,
    name: 'The Tower',
    class: 'major',
    number: 16,
    reverse: false,
  },
  {
    id: 17,
    name: 'The Star',
    class: 'major',
    number: 17,
    reverse: false,
  },
  {
    id: 18,
    name: 'The Moon',
    class: 'major',
    number: 18,
    reverse: false,
  },
  {
    id: 19,
    name: 'The Sun',
    class: 'major',
    number: 19,
    reverse: false,
  },
  {
    id: 20,
    name: 'Judgement',
    class: 'major',
    number: 20,
    reverse: false,
  },
  {
    id: 21,
    name: 'The World',
    class: 'major',
    number: 21,
    reverse: false,
  },
  {
    id: 22,
    name: 'Ace of Wands',
    class: 'wands',
    number: 1,
    reverse: false,
  },
  {
    id: 23,
    name: 'Two of Wands',
    class: 'wands',
    number: 2,
    reverse: false,
  },
  {
    id: 24,
    name: 'Three of Wands',
    class: 'wands',
    number: 3,
    reverse: false,
  },
  {
    id: 25,
    name: 'Four of Wands',
    class: 'wands',
    number: 4,
    reverse: false,
  },
  {
    id: 26,
    name: 'Five of Wands',
    class: 'wands',
    number: 5,
    reverse: false,
  },
  {
    id: 27,
    name: 'Six of Wands',
    class: 'wands',
    number: 6,
    reverse: false,
  },
  {
    id: 28,
    name: 'Seven of Wands',
    class: 'wands',
    number: 7,
    reverse: false,
  },
  {
    id: 29,
    name: 'Eight of Wands',
    class: 'wands',
    number: 8,
    reverse: false,
  },
  {
    id: 30,
    name: 'Nine of Wands',
    class: 'wands',
    number: 9,
    reverse: false,
  },
  {
    id: 31,
    name: 'Ten of Wands',
    class: 'wands',
    number: 10,
    reverse: false,
  },
  {
    id: 32,
    name: 'Page of Wands',
    class: 'wands',
    number: 11,
    reverse: false,
  },
  {
    id: 33,
    name: 'Knight of Wands',
    class: 'wands',
    number: 12,
    reverse: false,
  },
  {
    id: 34,
    name: 'Queen of Wands',
    class: 'wands',
    number: 13,
    reverse: false,
  },
  {
    id: 35,
    name: 'King of Wands',
    class: 'wands',
    number: 14,
    reverse: false,
  },
  {
    id: 36,
    name: 'Ace of Pentacles',
    class: 'pentacles',
    number: 1,
    reverse: false,
  },
  {
    id: 37,
    name: 'Two of Pentacles',
    class: 'pentacles',
    number: 2,
    reverse: false,
  },
  {
    id: 38,
    name: 'Three of Pentacles',
    class: 'pentacles',
    number: 3,
    reverse: false,
  },
  {
    id: 39,
    name: 'Four of Pentacles',
    class: 'pentacles',
    number: 4,
    reverse: false,
  },
  {
    id: 40,
    name: 'Five of Pentacles',
    class: 'pentacles',
    number: 5,
    reverse: false,
  },
  {
    id: 41,
    name: 'Six of Pentacles',
    class: 'pentacles',
    number: 6,
    reverse: false,
  },
  {
    id: 42,
    name: 'Seven of Pentacles',
    class: 'pentacles',
    number: 7,
    reverse: false,
  },
  {
    id: 43,
    name: 'Eight of Pentacles',
    class: 'pentacles',
    number: 8,
    reverse: false,
  },
  {
    id: 44,
    name: 'Nine of Pentacles',
    class: 'pentacles',
    number: 9,
    reverse: false,
  },
  {
    id: 45,
    name: 'Ten of Pentacles',
    class: 'pentacles',
    number: 10,
    reverse: false,
  },
  {
    id: 46,
    name: 'Page of Pentacles',
    class: 'pentacles',
    number: 11,
    reverse: false,
  },
  {
    id: 47,
    name: 'Knight of Pentacles',
    class: 'pentacles',
    number: 12,
    reverse: false,
  },
  {
    id: 48,
    name: 'Queen of Pentacles',
    class: 'pentacles',
    number: 13,
    reverse: false,
  },
  {
    id: 49,
    name: 'King of Pentacles',
    class: 'pentacles',
    number: 14,
    reverse: false,
  },
  {
    id: 50,
    name: 'Ace of Swords',
    class: 'swords',
    number: 1,
    reverse: false,
  },
  {
    id: 51,
    name: 'Two of Swords',
    class: 'swords',
    number: 2,
    reverse: false,
  },
  {
    id: 52,
    name: 'Three of Swords',
    class: 'swords',
    number: 3,
    reverse: false,
  },
  {
    id: 53,
    name: 'Four of Swords',
    class: 'swords',
    number: 4,
    reverse: false,
  },
  {
    id: 54,
    name: 'Five of Swords',
    class: 'swords',
    number: 5,
    reverse: false,
  },
  {
    id: 55,
    name: 'Six of Swords',
    class: 'swords',
    number: 6,
    reverse: false,
  },
  {
    id: 56,
    name: 'Seven of Swords',
    class: 'swords',
    number: 7,
    reverse: false,
  },
  {
    id: 57,
    name: 'Eight of Swords',
    class: 'swords',
    number: 8,
    reverse: false,
  },
  {
    id: 58,
    name: 'Nine of Swords',
    class: 'swords',
    number: 9,
    reverse: false,
  },
  {
    id: 59,
    name: 'Ten of Swords',
    class: 'swords',
    number: 10,
    reverse: false,
  },
  {
    id: 60,
    name: 'Page of Swords',
    class: 'swords',
    number: 11,
    reverse: false,
  },
  {
    id: 61,
    name: 'Knight of Swords',
    class: 'swords',
    number: 12,
    reverse: false,
  },
  {
    id: 62,
    name: 'Queen of Swords',
    class: 'swords',
    number: 13,
    reverse: false,
  },
  {
    id: 63,
    name: 'King of Swords',
    class: 'swords',
    number: 14,
    reverse: false,
  },
  {
    id: 64,
    name: 'Ace of Cups',
    class: 'cups',
    number: 1,
    reverse: false,
  },
  {
    id: 65,
    name: 'Two of Cups',
    class: 'cups',
    number: 2,
    reverse: false,
  },
  {
    id: 66,
    name: 'Three of Cups',
    class: 'cups',
    number: 3,
    reverse: false,
  },
  {
    id: 67,
    name: 'Four of Cups',
    class: 'cups',
    number: 4,
    reverse: false,
  },
  {
    id: 68,
    name: 'Five of Cups',
    class: 'cups',
    number: 5,
    reverse: false,
  },
  {
    id: 69,
    name: 'Six of Cups',
    class: 'cups',
    number: 6,
    reverse: false,
  },
  {
    id: 70,
    name: 'Seven of Cups',
    class: 'cups',
    number: 7,
    reverse: false,
  },
  {
    id: 71,
    name: 'Eight of Cups',
    class: 'cups',
    number: 8,
    reverse: false,
  },
  {
    id: 72,
    name: 'Nine of Cups',
    class: 'cups',
    number: 9,
    reverse: false,
  },
  {
    id: 73,
    name: 'Ten of Cups',
    class: 'cups',
    number: 10,
    reverse: false,
  },
  {
    id: 74,
    name: 'Page of Cups',
    class: 'cups',
    number: 11,
    reverse: false,
  },
  {
    id: 75,
    name: 'Knight of Cups',
    class: 'cups',
    number: 12,
    reverse: false,
  },
  {
    id: 76,
    name: 'Queen of Cups',
    class: 'cups',
    number: 13,
    reverse: false,
  },
  {
    id: 77,
    name: 'King of Cups',
    class: 'cups',
    number: 14,
    reverse: false,
  },
  {
    id: 78,
    name: 'The Fool(Reverse)',
    class: 'major',
    number: 0,
    reverse: true,
  },
  {
    id: 79,
    name: 'The Magician(Reverse)',
    class: 'major',
    number: 1,
    reverse: true,
  },
  {
    id: 80,
    name: 'The High Priestess(Reverse)',
    class: 'major',
    number: 2,
    reverse: true,
  },
  {
    id: 81,
    name: 'The Empress(Reverse)',
    class: 'major',
    number: 3,
    reverse: true,
  },
  {
    id: 82,
    name: 'The Emperor(Reverse)',
    class: 'major',
    number: 4,
    reverse: true,
  },
  {
    id: 83,
    name: 'The Hierophant(Reverse)',
    class: 'major',
    number: 5,
    reverse: true,
  },
  {
    id: 84,
    name: 'The Lovers(Reverse)',
    class: 'major',
    number: 6,
    reverse: true,
  },
  {
    id: 85,
    name: 'The Chariot(Reverse)',
    class: 'major',
    number: 7,
    reverse: true,
  },
  {
    id: 86,
    name: 'Strength(Reverse)',
    class: 'major',
    number: 8,
    reverse: true,
  },
  {
    id: 87,
    name: 'The Hermit(Reverse)',
    class: 'major',
    number: 9,
    reverse: true,
  },
  {
    id: 88,
    name: 'Wheel of Fortune(Reverse)',
    class: 'major',
    number: 10,
    reverse: true,
  },
  {
    id: 89,
    name: 'Justice(Reverse)',
    class: 'major',
    number: 11,
    reverse: true,
  },
  {
    id: 90,
    name: 'The Hanged Man(Reverse)',
    class: 'major',
    number: 12,
    reverse: true,
  },
  {
    id: 91,
    name: 'Death(Reverse)',
    class: 'major',
    number: 13,
    reverse: true,
  },
  {
    id: 92,
    name: 'Temperance(Reverse)',
    class: 'major',
    number: 14,
    reverse: true,
  },
  {
    id: 93,
    name: 'The Devil(Reverse)',
    class: 'major',
    number: 15,
    reverse: true,
  },
  {
    id: 94,
    name: 'The Tower(Reverse)',
    class: 'major',
    number: 16,
    reverse: true,
  },
  {
    id: 95,
    name: 'The Star(Reverse)',
    class: 'major',
    number: 17,
    reverse: true,
  },
  {
    id: 96,
    name: 'The Moon(Reverse)',
    class: 'major',
    number: 18,
    reverse: true,
  },
  {
    id: 97,
    name: 'The Sun(Reverse)',
    class: 'major',
    number: 19,
    reverse: true,
  },
  {
    id: 98,
    name: 'Judgement(Reverse)',
    class: 'major',
    number: 20,
    reverse: true,
  },
  {
    id: 99,
    name: 'The World(Reverse)',
    class: 'major',
    number: 21,
    reverse: true,
  },
  {
    id: 100,
    name: 'Ace of Wands(Reverse)',
    class: 'wands',
    number: 1,
    reverse: true,
  },
  {
    id: 101,
    name: 'Two of Wands(Reverse)',
    class: 'wands',
    number: 2,
    reverse: true,
  },
  {
    id: 102,
    name: 'Three of Wands(Reverse)',
    class: 'wands',
    number: 3,
    reverse: true,
  },
  {
    id: 103,
    name: 'Four of Wands(Reverse)',
    class: 'wands',
    number: 4,
    reverse: true,
  },
  {
    id: 104,
    name: 'Five of Wands(Reverse)',
    class: 'wands',
    number: 5,
    reverse: true,
  },
  {
    id: 105,
    name: 'Six of Wands(Reverse)',
    class: 'wands',
    number: 6,
    reverse: true,
  },
  {
    id: 106,
    name: 'Seven of Wands(Reverse)',
    class: 'wands',
    number: 7,
    reverse: true,
  },
  {
    id: 107,
    name: 'Eight of Wands(Reverse)',
    class: 'wands',
    number: 8,
    reverse: true,
  },
  {
    id: 108,
    name: 'Nine of Wands(Reverse)',
    class: 'wands',
    number: 9,
    reverse: true,
  },
  {
    id: 109,
    name: 'Ten of Wands(Reverse)',
    class: 'wands',
    number: 10,
    reverse: true,
  },
  {
    id: 110,
    name: 'Page of Wands(Reverse)',
    class: 'wands',
    number: 11,
    reverse: true,
  },
  {
    id: 111,
    name: 'Knight of Wands(Reverse)',
    class: 'wands',
    number: 12,
    reverse: true,
  },
  {
    id: 112,
    name: 'Queen of Wands(Reverse)',
    class: 'wands',
    number: 13,
    reverse: true,
  },
  {
    id: 113,
    name: 'King of Wands(Reverse)',
    class: 'wands',
    number: 14,
    reverse: true,
  },
  {
    id: 114,
    name: 'Ace of Pentacles(Reverse)',
    class: 'pentacles',
    number: 1,
    reverse: true,
  },
  {
    id: 115,
    name: 'Two of Pentacles(Reverse)',
    class: 'pentacles',
    number: 2,
    reverse: true,
  },
  {
    id: 116,
    name: 'Three of Pentacles(Reverse)',
    class: 'pentacles',
    number: 3,
    reverse: true,
  },
  {
    id: 117,
    name: 'Four of Pentacles(Reverse)',
    class: 'pentacles',
    number: 4,
    reverse: true,
  },
  {
    id: 118,
    name: 'Five of Pentacles(Reverse)',
    class: 'pentacles',
    number: 5,
    reverse: true,
  },
  {
    id: 119,
    name: 'Six of Pentacles(Reverse)',
    class: 'pentacles',
    number: 6,
    reverse: true,
  },
  {
    id: 120,
    name: 'Seven of Pentacles(Reverse)',
    class: 'pentacles',
    number: 7,
    reverse: true,
  },
  {
    id: 121,
    name: 'Eight of Pentacles(Reverse)',
    class: 'pentacles',
    number: 8,
    reverse: true,
  },
  {
    id: 122,
    name: 'Nine of Pentacles(Reverse)',
    class: 'pentacles',
    number: 9,
    reverse: true,
  },
  {
    id: 123,
    name: 'Ten of Pentacles(Reverse)',
    class: 'pentacles',
    number: 10,
    reverse: true,
  },
  {
    id: 124,
    name: 'Page of Pentacles(Reverse)',
    class: 'pentacles',
    number: 11,
    reverse: true,
  },
  {
    id: 125,
    name: 'Knight of Pentacles(Reverse)',
    class: 'pentacles',
    number: 12,
    reverse: true,
  },
  {
    id: 126,
    name: 'Queen of Pentacles(Reverse)',
    class: 'pentacles',
    number: 13,
    reverse: true,
  },
  {
    id: 127,
    name: 'King of Pentacles(Reverse)',
    class: 'pentacles',
    number: 14,
    reverse: true,
  },
  {
    id: 128,
    name: 'Ace of Swords(Reverse)',
    class: 'swords',
    number: 1,
    reverse: true,
  },
  {
    id: 129,
    name: 'Two of Swords(Reverse)',
    class: 'swords',
    number: 2,
    reverse: true,
  },
  {
    id: 130,
    name: 'Three of Swords(Reverse)',
    class: 'swords',
    number: 3,
    reverse: true,
  },
  {
    id: 131,
    name: 'Four of Swords(Reverse)',
    class: 'swords',
    number: 4,
    reverse: true,
  },
  {
    id: 132,
    name: 'Five of Swords(Reverse)',
    class: 'swords',
    number: 5,
    reverse: true,
  },
  {
    id: 133,
    name: 'Six of Swords(Reverse)',
    class: 'swords',
    number: 6,
    reverse: true,
  },
  {
    id: 134,
    name: 'Seven of Swords(Reverse)',
    class: 'swords',
    number: 7,
    reverse: true,
  },
  {
    id: 135,
    name: 'Eight of Swords(Reverse)',
    class: 'swords',
    number: 8,
    reverse: true,
  },
  {
    id: 136,
    name: 'Nine of Swords(Reverse)',
    class: 'swords',
    number: 9,
    reverse: true,
  },
  {
    id: 137,
    name: 'Ten of Swords(Reverse)',
    class: 'swords',
    number: 10,
    reverse: true,
  },
  {
    id: 138,
    name: 'Page of Swords(Reverse)',
    class: 'swords',
    number: 11,
    reverse: true,
  },
  {
    id: 139,
    name: 'Knight of Swords(Reverse)',
    class: 'swords',
    number: 12,
    reverse: true,
  },
  {
    id: 140,
    name: 'Queen of Swords(Reverse)',
    class: 'swords',
    number: 13,
    reverse: true,
  },
  {
    id: 141,
    name: 'King of Swords(Reverse)',
    class: 'swords',
    number: 14,
    reverse: true,
  },
  {
    id: 142,
    name: 'Ace of Cups(Reverse)',
    class: 'cups',
    number: 1,
    reverse: true,
  },
  {
    id: 143,
    name: 'Two of Cups(Reverse)',
    class: 'cups',
    number: 2,
    reverse: true,
  },
  {
    id: 144,
    name: 'Three of Cups(Reverse)',
    class: 'cups',
    number: 3,
    reverse: true,
  },
  {
    id: 145,
    name: 'Four of Cups(Reverse)',
    class: 'cups',
    number: 4,
    reverse: true,
  },
  {
    id: 146,
    name: 'Five of Cups(Reverse)',
    class: 'cups',
    number: 5,
    reverse: true,
  },
  {
    id: 147,
    name: 'Six of Cups(Reverse)',
    class: 'cups',
    number: 6,
    reverse: true,
  },
  {
    id: 148,
    name: 'Seven of Cups(Reverse)',
    class: 'cups',
    number: 7,
    reverse: true,
  },
  {
    id: 149,
    name: 'Eight of Cups(Reverse)',
    class: 'cups',
    number: 8,
    reverse: true,
  },
  {
    id: 150,
    name: 'Nine of Cups(Reverse)',
    class: 'cups',
    number: 9,
    reverse: true,
  },
  {
    id: 151,
    name: 'Ten of Cups(Reverse)',
    class: 'cups',
    number: 10,
    reverse: true,
  },
  {
    id: 152,
    name: 'Page of Cups(Reverse)',
    class: 'cups',
    number: 11,
    reverse: true,
  },
  {
    id: 153,
    name: 'Knight of Cups(Reverse)',
    class: 'cups',
    number: 12,
    reverse: true,
  },
  {
    id: 154,
    name: 'Queen of Cups(Reverse)',
    class: 'cups',
    number: 13,
    reverse: true,
  },
  {
    id: 155,
    name: 'King of Cups(Reverse)',
    class: 'cups',
    number: 14,
    reverse: true,
  },
];
