pipeline {
    agent any
         environment {
            imagename = "d107final/arcana-ai"
            registryCredential = 'jumzip@d107'
            dockerImage = ''
        }

    //tools {}
    stages {
        stage('start') {
            steps { echo '[process START] (o゜▽゜)o---☆ *:･.:･ﾟ*' }
        }

        stage('git clone') {
            steps {
                checkout scmGit(
                    branches: [[name: 'aeoragy-ai']],
                    extensions: [],
                    userRemoteConfigs: [[
                        credentialsId: 'arcanaJenkins',
                        url: 'https://lab.ssafy.com/s08-final/S08P31D107.git'
                    ]]
                )
            }
            post {
                success { echo 'clone Git complete!!!' }
                failure { echo '[error] git clone FAIL (╯°□°）╯︵ ┻━┻ ' }
            }
        }

        stage('build Docker') {

            steps {
                dir('ai') {

                    echo 'build Docker...'

                    //현재 dir 체크
                    script {
                        def pwd = sh(script: 'pwd', returnStdout: true).trim()
                        echo "Current directory : ${pwd}"

                        dockerImage = docker.build imagename
                    }
                }
            }

            post {
                success { echo 'build Docker complete!!!' }
                failure { echo '[error] build Docker FAIL (╯°□°）╯︵ ┻━┻ ' }
            }
        }

        stage('push Docker') {
            steps {
                echo 'push Docker...'
                
                script {
                    docker.withRegistry('', registryCredential) {
                        dockerImage.push() 
                    }
                }
            }

            post {
                success { echo 'build Docker complete!!!' }
                failure { echo '[error] push Docker FAIL (╯°□°）╯︵ ┻━┻ ' }
            }
        }

        stage('run Docker') {
            steps {
                echo 'pull Docker...'

                sh 'docker pull d107final/arcana-ai'

                echo 'Clean image...'
                sh '''
                    if test "`docker ps -aq --filter name=arcana-ai`"; then
                    docker stop arcana-ai
                    docker rm arcana-ai
                    fi
                '''

                echo 'run Docker...'
                sh 'docker run -d --name arcana-ai -p 19102:18082 d107final/arcana-ai'

            }
        }
    }
}
